name: ❓ Question
description: Ask question related to this app.
labels:
- question
body:
- type: markdown
  attributes:
    value: Please make sure to [search for existing issues](./issues?q=) before filing a new one!

- type: textarea
  attributes:
    label: Question
    description: Question.
  validations:
    required: true